version: '3'
services:
  vue-site:
    build:
      context: ./
      dockerfile: vue.dockerfile
    container_name: vue-site
    ports:
      - 9080:8080
      - 9001:8000
    environment:
      TZ: "Asia/Tokyo"
    command: "tail -f /dev/null"
    networks:
      seventh-project-net:
    volumes:
      - ./vue.js:/app
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
    networks:
      seventh-project-net:
    volumes:
      - ./nginx:/var/www
  flask:
    build:
      context: ./
      dockerfile: flask.dockerfile
    container_name: flask
    ports:
      - 6000
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # command: 
    #   - "/bin/bash"
    #   - "-c"
    #   - >
    #     chmod 755 /app/uwsgi.ini;
    #     uwsgi --ini /app/uwsgi.ini;
    command: /bin/bash -c "tail -f /dev/null"
    networks:
      seventh-project-net:
    volumes:
      - ./flask:/app/site
  postgres:
    image: postgres:11.2
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      seventh-project-net:
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  seventh-project-net:
      driver: bridge
      ipam:
          driver: default
          config:
            - subnet: 172.10.0.0/24
