version: '3'
services:
  vue-site:
    build:
      context: ./
      dockerfile: vue.dockerfile
    container_name: vue-site
    ports:
      - 9080:8080
      - 9001:8000
    environment:
      TZ: "Asia/Tokyo"
    command: "tail -f /dev/null"
    networks:
      seventh-project-net:
    volumes:
      - ./vue.js:/app
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
    networks:
      seventh-project-net:
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./nginx:/var/www
  flask:
    build:
      context: ./
      dockerfile: flask.dockerfile
    container_name: flask
    ports:
      - 6000
    environment:
      TZ: "Asia/Tokyo"
    # command:  ["uwsgi --ini /app/uwsgi.ini"]
    command: "tail -f /dev/null"
    networks:
      seventh-project-net:
    volumes:
      - ./flask:/app/site
    
  # oracle:
  #   image: oracle/database:18.3.0-ee
  #   container_name: oracle-server
  #   ports:
  #     - 1521:1521
  #     - 5500:5500
  #   networks:
  #     kotlin-go-cpp-net2:
  #   volumes:
  #     - ./oracle:/opt/oracle/oradata
  #   environment:
  #     - TZ=Asia/Tokyo
  #     - ORACLE_SID=ORCL
  #     - ORACLE_PDB=ThirdProject
  #     - ORACLE_PWD=oracle
  #     - ORACLE_CHARACTERSET=AL32UTF8
  #     - NLS_LANG=Japanese_Japan.AL32UTF8
networks:
  seventh-project-net:
      driver: bridge
      ipam:
          driver: default
          config:
            - subnet: 172.10.0.0/24
