"""empty message

Revision ID: 1052fc5948f5
Revises: 291b60cd9774
Create Date: 2019-08-19 21:42:34.838774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1052fc5948f5'
down_revision = '291b60cd9774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('mimetype', sa.String(length=100), nullable=True))
    op.drop_column('photos', 'content_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('photos', 'mimetype')
    # ### end Alembic commands ###
