"""empty message

Revision ID: 29af61d85562
Revises: 503465ceb072
Create Date: 2019-09-02 11:26:00.049055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29af61d85562'
down_revision = '503465ceb072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('account', sa.String(length=255), nullable=False))
    op.add_column('contacts', sa.Column('created_datetime', sa.DateTime(), nullable=False))
    op.add_column('contacts', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('contacts', sa.Column('message', sa.String(length=5000), nullable=False))
    op.add_column('contacts', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('contacts', sa.Column('organization', sa.String(length=16), nullable=False))
    op.add_column('contacts', sa.Column('phone', sa.String(length=16), nullable=True))
    op.add_column('contacts', sa.Column('state', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'state')
    op.drop_column('contacts', 'phone')
    op.drop_column('contacts', 'organization')
    op.drop_column('contacts', 'name')
    op.drop_column('contacts', 'message')
    op.drop_column('contacts', 'email')
    op.drop_column('contacts', 'created_datetime')
    op.drop_column('contacts', 'account')
    # ### end Alembic commands ###
