"""empty message

Revision ID: 49a59c4e58ba
Revises: 4e3af29a6831
Create Date: 2019-08-19 20:53:16.565130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a59c4e58ba'
down_revision = '4e3af29a6831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('extension', sa.String(length=10), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('modified_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('name', sa.String(length=200), nullable=True))
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('user', 'name')
    op.drop_table('photos')
    # ### end Alembic commands ###
