"""empty message

Revision ID: 503465ceb072
Revises: c17906b7e520
Create Date: 2019-09-02 11:25:49.428361

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '503465ceb072'
down_revision = 'c17906b7e520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'email')
    op.drop_column('contacts', 'message')
    op.drop_column('contacts', 'state')
    op.drop_column('contacts', 'phone')
    op.drop_column('contacts', 'created_datetime')
    op.drop_column('contacts', 'name')
    op.drop_column('contacts', 'organization')
    op.drop_column('contacts', 'account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('account', sa.VARCHAR(length=355), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('organization', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('created_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('phone', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('contacts', sa.Column('state', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('message', sa.VARCHAR(length=5000), autoincrement=False, nullable=False))
    op.add_column('contacts', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
