"""empty message

Revision ID: 808fbf35a6b8
Revises: c9ab6ac75bd5
Create Date: 2019-09-07 09:40:54.066077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808fbf35a6b8'
down_revision = 'c9ab6ac75bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photographs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_title', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('mimetype', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.Binary(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photographs')
    # ### end Alembic commands ###
