"""empty message

Revision ID: 920004a219ed
Revises: 955a27612d42
Create Date: 2019-10-11 14:57:15.329042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '920004a219ed'
down_revision = '955a27612d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mimetype', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('created_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='photos_pkey')
    )
    # ### end Alembic commands ###
