"""empty message

Revision ID: af3e5910bd14
Revises: 1052fc5948f5
Create Date: 2019-08-19 21:43:24.544399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3e5910bd14'
down_revision = '1052fc5948f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'extension')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('extension', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
