"""empty message

Revision ID: c17906b7e520
Revises: fe44f0915254
Create Date: 2019-09-02 11:21:24.895733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17906b7e520'
down_revision = 'fe44f0915254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=355), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('organization', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=5000), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    # ### end Alembic commands ###
