"""empty message

Revision ID: c6eae4cc3bad
Revises: 808fbf35a6b8
Create Date: 2019-09-07 09:52:24.703745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6eae4cc3bad'
down_revision = '808fbf35a6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photograph_id', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.Binary(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.Column('modified_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['photograph_id'], ['photographs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_photograph_id'), 'videos', ['photograph_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_photograph_id'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
