"""empty message

Revision ID: c9ab6ac75bd5
Revises: f988bf0d463f
Create Date: 2019-09-04 11:48:46.198045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ab6ac75bd5'
down_revision = 'f988bf0d463f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_uid_key', 'contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contacts_uid_key', 'contacts', ['uid'])
    # ### end Alembic commands ###
